import type {Analysis,Deadline,Decision,Finding,Message,Priority,Question,Task} from '../types';
const word=(s:string)=>s.toLowerCase();
const priority=(score:number):Priority=>score>=88?'Critical':score>=68?'High':score>=42?'Medium':score>=20?'Low':'Informational';
const deadlineFor=(text:string):Deadline|undefined=>{const m=text.match(/\b(today|tomorrow|tonight|by\s+(?:\w+)|next\s+\w+|\b(?:october|november|december|january|february|march|april|may|june|july|august|september)\s+\d{1,2}|\d{4}-\d\d-\d\d|\d{1,2}\/\d{1,2}\/\d{4})\b/i); if(!m)return; const original=m[0]; const ambiguous=/next\s+\w+|by\s+\w+/i.test(original); return {original,label:ambiguous?`${original} · resolve against conversation date`:original,ambiguous};};
export function analyze(messages:Message[], userName='Alex'):Analysis{
 const tasks:Task[]=[], deadlines:Deadline[]=[], decisions:Decision[]=[], questions:Question[]=[], findings:Finding[]=[], mentions:string[]=[];
 messages.forEach(msg=>{const t=word(msg.text); const dl=deadlineFor(msg.text); if(dl) deadlines.push(dl);
  const direct=new RegExp(`(^|[^a-z])${userName.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&').toLowerCase()}([^a-z]|$)`,'i').test(msg.text)||msg.text.includes(`@${userName}`); if(direct)mentions.push(msg.id);
  const taskSignal=/\b(please|could you|can you|need to|review|submit|fix|prepare|confirm|post|record|send|complete)\b/i.test(msg.text); if(taskSignal&&!/^proposal/i.test(msg.text)){let score=direct?78:58;if(dl)score+=15; const p=priority(score); tasks.push({id:`task-${tasks.length+1}`,description:msg.text.replace(/^(please|could you|can you)\s*/i,''),sourceId:msg.id,sender:msg.sender,deadline:dl,priority:p,confidence:direct?.92:.76,status:/finished|complete|passing|done/i.test(msg.text)?'completed':'open',reason:[direct?'direct mention':'explicit action language',dl?'deadline present':''].filter(Boolean).join(' · ')});}
  if(/\bdecision\b|\bwill ship\b|\bwe will\b/i.test(msg.text))decisions.push({id:`d-${decisions.length+1}`,statement:msg.text,type:/decision:|we will/i.test(msg.text)?'confirmed':'recommendation',sourceId:msg.id,sender:msg.sender,confidence:.9});
  if(/\bproposal\b|\bmaybe\b|\bconsider\b/i.test(msg.text))decisions.push({id:`d-${decisions.length+1}`,statement:msg.text,type:'tentative',sourceId:msg.id,sender:msg.sender,confidence:.74});
  if(msg.text.includes('?'))questions.push({id:`q-${questions.length+1}`,text:msg.text,sourceId:msg.id,sender:msg.sender,potentiallyUnanswered:!messages.slice(messages.indexOf(msg)+1).some(n=>n.sender!==msg.sender&&n.text.length>20),resolved:false});
  let score=0; const reasons:string[]=[]; if(direct){score+=28;reasons.push('mentions your configured name');} if(dl){score+=25;reasons.push('contains a deadline');} if(/urgent|blocking|failing|due|please/i.test(msg.text)){score+=22;reasons.push('signals time pressure or action');} if(/decision|confirmed|will ship/i.test(msg.text)){score+=20;reasons.push('records a project decision');} if(score){const p=priority(score);findings.push({id:`f-${findings.length+1}`,kind:direct?'mention':'priority',title:p==='Critical'?'Needs attention now':p==='High'?'Important follow-up':'Signal detected',detail:reasons.join(' · '),sourceIds:[msg.id],priority:p,score});}
 });
 const topic=messages.slice(0,3).map(m=>m.text.split(/[.!?]/)[0]).join(' · ').slice(0,120)||'Untitled conversation'; const open=tasks.filter(t=>t.status==='open').length; const summary=`${messages.length} messages reviewed locally. ${tasks.length} action items surfaced (${open} open), ${decisions.filter(d=>d.type==='confirmed').length} confirmed decisions, and ${questions.filter(q=>q.potentiallyUnanswered).length} questions may still need an answer.`;
 return {summary,topic,findings:findings.sort((a,b)=>b.score-a.score),tasks,decisions,questions,deadlines,mentions,analyzedAt:new Date().toISOString(),engineVersion:'rule-based-1.0'};
}
